/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemoteSessionIdRouteImport } from './routes/remote.$sessionId'
import { Route as ApiReactorTokenRouteImport } from './routes/api.reactor.token'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteSessionIdRoute = RemoteSessionIdRouteImport.update({
  id: '/remote/$sessionId',
  path: '/remote/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReactorTokenRoute = ApiReactorTokenRouteImport.update({
  id: '/api/reactor/token',
  path: '/api/reactor/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/remote/$sessionId': typeof RemoteSessionIdRoute
  '/api/reactor/token': typeof ApiReactorTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/remote/$sessionId': typeof RemoteSessionIdRoute
  '/api/reactor/token': typeof ApiReactorTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/remote/$sessionId': typeof RemoteSessionIdRoute
  '/api/reactor/token': typeof ApiReactorTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/library'
    | '/remote/$sessionId'
    | '/api/reactor/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/library'
    | '/remote/$sessionId'
    | '/api/reactor/token'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/library'
    | '/remote/$sessionId'
    | '/api/reactor/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  LibraryRoute: typeof LibraryRoute
  RemoteSessionIdRoute: typeof RemoteSessionIdRoute
  ApiReactorTokenRoute: typeof ApiReactorTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$sessionId': {
      id: '/remote/$sessionId'
      path: '/remote/$sessionId'
      fullPath: '/remote/$sessionId'
      preLoaderRoute: typeof RemoteSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reactor/token': {
      id: '/api/reactor/token'
      path: '/api/reactor/token'
      fullPath: '/api/reactor/token'
      preLoaderRoute: typeof ApiReactorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  LibraryRoute: LibraryRoute,
  RemoteSessionIdRoute: RemoteSessionIdRoute,
  ApiReactorTokenRoute: ApiReactorTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
