alter table public.presets
  add column if not exists thumbnail_url text,
  add column if not exists ref_image_url text;

insert into public.presets (user_id, name, emoji, prompt, requires_ref, sort_order, thumbnail_url, ref_image_url) values
(null, 'Hooded Windbreaker', '🧥', 'Replace the character in the video with the man from the reference image, keeping his full black beard, short dark hair, and glossy black nylon windbreaker with the hood up and thin drawstrings hanging loose. Keep his identity and face unchanged.', true, 200, '/__l5e/assets-v1/d06c5cfa-b7b3-4c49-bbf5-091052032ccd/kanye.webp', '/__l5e/assets-v1/d06c5cfa-b7b3-4c49-bbf5-091052032ccd/kanye.webp'),
(null, 'NFL Night', '🏟️', 'Change the background to a packed football stadium at night seen from the upper deck, with a green field marked in white yard lines, glowing ribbon boards wrapping every tier, bright floodlights, and fans in green and white filling the stands.', false, 210, '/__l5e/assets-v1/1b588f0d-ecf2-4149-a616-ec3922d28dda/metlife2.jpg', null),
(null, 'Leather Vest', '🎤', 'Replace the character in the video with the man from the reference image, keeping his slicked-back braided hair, full dark beard, silver chain necklaces, tattooed forearms, and black leather vest over a fitted black t-shirt. Keep his smile and identity unchanged.', true, 220, '/__l5e/assets-v1/0dba1501-a924-4943-a014-68822d8adcb4/drake.webp', '/__l5e/assets-v1/0dba1501-a924-4943-a014-68822d8adcb4/drake.webp'),
(null, 'Soccer Daylight', '⚽', 'Change the background to a sunlit open-air stadium during a soccer match, with a bright green pitch, three tiers of fans dressed in red, large video screens along the upper rim, and a partly cloudy blue sky.', false, 230, '/__l5e/assets-v1/c82e0d77-c307-4293-8658-faaab3cdb481/metlife-stadium-photo.webp', null),
(null, 'Streamer', '💻', 'Replace the character in the video with the young man from the reference image, keeping his bleached blond fringe with dark roots, black rectangular glasses, wide smile, and black t-shirt. Keep his identity and face unchanged.', true, 240, '/__l5e/assets-v1/cda52f0c-366d-4a21-9598-96b28c969f4c/neon.webp', '/__l5e/assets-v1/cda52f0c-366d-4a21-9598-96b28c969f4c/neon.webp'),
(null, 'Pink Stripe Kit', '🌸', 'Replace the character in the video with the man from the reference image, keeping his short brown hair, ginger-brown beard, wide smile, and black athletic jersey with thin pink stripes on the shoulders. Keep his identity and face unchanged.', true, 250, '/__l5e/assets-v1/e108caa2-e4ad-4f60-8a0e-1e77e76c5c42/mbappe.webp', '/__l5e/assets-v1/e108caa2-e4ad-4f60-8a0e-1e77e76c5c42/mbappe.webp');