// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // TanStack also executes the client middleware phase during SSR. Avoid
    // constructing the browser Supabase client in the Worker runtime.
    if (typeof window === 'undefined') {
      return next()
    }

    // Keep the browser client out of the Worker startup graph entirely.
    // A runtime guard alone is insufficient because static imports are still
    // evaluated while the server bundle initializes.
    const { supabase } = await import('./client')
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
