// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmiwbfvsqqmlpdxanttp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptaXdiZnZzcXFtbHBkeGFudHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0MTQ2MDEsImV4cCI6MjA5OTk5MDYwMX0.XCBnOw1a9nMJm568I4GoU_TgHi7ooowupHeBHO2W7Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});